[tool.poetry]
name = "stream2podcast"
version = "0.1.0"
description = "Convert an audio stream to a podcast feed"
authors = ["roedebaron"]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.28.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
