version: "3.8"

# This compose config should not be run directly.
# Instead, use 'docker_run.py' with a 'docker.<env>.ini' file to ensure host is configured correctly.

name: stream2podcast # Project name avoids parent folder prefix

services:
  recorder:
    restart: on-failure:5 # Max 5 retries
    build:
      context: ../recording-service
      dockerfile: ../docker/Dockerfile
    # These volumes are expected to exist on host and accessible by the container user
    volumes:
      - ${RECORDER_CONFIG_PATH?}:/app/config.yml:ro
      - ${DATA_DIR?}:/app/recordings

    # Run as this (unprivileged) user instead of root.
    user: "${DOCKER_USER_ID?}:${DOCKER_GROUP_ID?}"
    environment:
      - POETRY_VIRTUALENVS_CREATE=false # Set poetry config for docker user. Use system env. in container instead of creating a virtualenv
      - PYTHONUNBUFFERED=1 # Prevents Python from buffering stdout and stder

  feed:
    restart: on-failure:5
    build:
      context: ../feed-service
      dockerfile: ../docker/Dockerfile
    volumes:
      - ${FEED_CONFIG_PATH?}:/app/config.yml:ro
      - ${DATA_DIR?}:/app/recordings

    user: "${DOCKER_USER_ID?}:${DOCKER_GROUP_ID?}"
    environment:
      - POETRY_VIRTUALENVS_CREATE=false
      - PYTHONUNBUFFERED=1
