version: "3.8"

services:
  stream2podcast:
    restart: "always"
    build:
      context: ..
      dockerfile: docker/Dockerfile
    # Mount config file at startup (left path should be local path of your config file)
    volumes:
      - ${CONFIG_PATH:-../../config.json}:/app/config.json:ro  # Will use CONFIG_PATH if non-empty
      - ../recordings:/app/recordings # Save recordings to local folder on host
