version: "3.8"

# Docker compose config for development. First ensure host paths are correct, then run:
# docker-compose up --build

name: stream2podcast

services:
  recorder:
    build:
      context: ../recording-service
      dockerfile: ../docker/Dockerfile
    volumes:
      - ../config.recording.yml:/app/config.yml:ro
      - ../recordings:/app/recordings
    environment:
      - PYTHONUNBUFFERED=1
      - POETRY_VIRTUALENVS_CREATE=false

  feed:
    restart: on-failure:5
    build:
      context: ../feed-service
      dockerfile: ../docker/Dockerfile
    volumes:
      - ../config.feed.yml:/app/config.yml:ro
      - ../recordings:/app/recordings
    environment:
      - PYTHONUNBUFFERED=1
      - POETRY_VIRTUALENVS_CREATE=false
