stream_url: "https://example.com"
output_dir: "../recordings" # Directory where recordings should be saved
time_zone: "Europe/Berlin" # IANA time zone name. See https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Specify one or more recording schedules
recording_schedules:
    - title: "morning program every weekday" # Will be used as the title of the podcast feed
      start_timeofday: "06:15" # Time as HH:MM (24-hour clock) in the specified time zone
      end_timeofday: "07:00"

      frequency: "mon, tue, wed, thu, fri" # Optional, defaults to '*' i.e. every day
      description: "This is a morning program" # Optional, will be used as the podcast description when generating the feed
      image_url: "https://example.com/image.png" # Optional, will be used as the podcast image when generating the feed

    - title: "afternoon program every weekday"
      start_timeofday: "13:05"
      end_timeofday: "14:00"
      frequency: "mon-fri" # Optional

    - title: "evening program every tuesday and friday"
      start_timeofday: "19:30"
      end_timeofday: "21:00"
      frequency: "tue, fri" # Optional
