stream_url: "https://example.com"
output_dir: "../recordings" # Directory where recordings should be saved
time_zone: "Europe/Berlin" # IANA time zone name. See https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Time periods to record the stream every day
recording_schedules:
    - title: "morning program" # Will be used as the title of the podcast feed
      start_timeofday: "06:15" # Time as HH:MM (24-hour clock) in the specified time zone
      end_timeofday: "07:00"
      description: "This is a morning program" # Optional, will be used as the description of the podcast feed
      image_url: "https://example.com/image.png" # Optional, will be used as the image of the podcast feed

    - title: "afternoon program"
      start_timeofday: "13:05"
      end_timeofday: "14:00"

    - title: "evening program"
      start_timeofday: "19:30"
      end_timeofday: "21:00"
