# Directory where feed-service should look for recordings.
base_dir: "../recordings"

# Base URL where the podcast feeds are served from
base_url: "https://podcasts.mydomain.com/"

# OPTIONAL: Whether to update feeds on startup. Defaults to false.
should_update_feeds_on_startup: true
