name: cicd

on:
    push:
        branches:
            - "*"
        paths:
            - "recording-service/**"
            - "!**.md"
    pull_request:
        branches:
            - "*"
        paths:
            - "recording-service/**"
            - "!**.md"

jobs:
    lint-and-test:
        runs-on: ubuntu-latest
        steps:
            # Use resuable workflow
            - uses: ./.github/workflows/reusable-workflow.yml
              with:
                  project_dir: recording-service
