on:
    push:
        branches-ignore:
            - main
        # paths:
        # - "recording-service/**"
    pull_request:
        branches:
            - "*"
        # paths:
        # - "recording-service/**"

jobs:
    lint-and-test:
        uses: ./.github/workflows/reusable-workflow.yml
        with:
            project_dir: "recording-service"
