on:
    push:
        branches-ignore:
            - main
        paths:
            - "feed-service/**"

    pull_request:
        branches:
            - "*"
        paths:
            - "feed-service/**"

jobs:
    feed-service:
        uses: ./.github/workflows/lint-and-test.yml
        with:
            project_dir: "feed-service"
