on:
    push:
        branches:
            - "main"

        paths:
            - "recording-service/**"

jobs:
    lint-and-test:
        uses: ./.github/workflows/lint-and-test.yml
        with:
            project_dir: "recording-service"

    build-and-push:
        needs: lint-and-test
        uses: ./.github/workflows/build-and-push.yml
        with:
            project_dir: "recording-service"
        secrets: inherit
