on:
    workflow_call:
        inputs:
            project_dir:
                required: true
                type: string

jobs:
    lint-and-test:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ${{ inputs.project_dir }}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"
                  cache: "pip"

            - run: |
                  pip install poetry
                  poetry config virtualenvs.create false

            # Install all deps. for pyright to be able to run type checking
            - run: poetry install

            # Lint with type checking
            - run: black --check .
            - run: isort --check .
            - run: pyright

            - name: Run Tests
              run: python -m pytest
